"""Added 'reply_to_comment' field to Comment2

Revision ID: 1a0023ba838a
Revises: b9e01b0bad41
Create Date: 2024-08-14 19:37:44.363632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0023ba838a'
down_revision: Union[str, None] = 'b9e01b0bad41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
