"""Added 'reply_to_comment' field to Comment3

Revision ID: 242f8d1f1ef6
Revises: 1a0023ba838a
Create Date: 2024-08-14 19:39:29.963291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242f8d1f1ef6'
down_revision: Union[str, None] = '1a0023ba838a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
